{
 "title": "PingDirectory Per-Server Dashboard",
 "description": "PingDirectory Metrics by Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "${PING_IDENTITY_K8S_NAMESPACE}" }
  ]
 },
 "panels": [
  {
   "title": "Throughput by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput by Operation and Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "throughput{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Average Operation Latency by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (response_time{namespace=\"$namespace\"} > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Latency by Operation and Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "response_time{namespace=\"$namespace\"} > 0",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Rate by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Collections per Minute" }
   ],
   "targets": [
    {
     "expr": "sum by (gcType, size, cause, instance) (rate(garbage_collections{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{instance}}-{{gcType}}-{{size}}-{{cause}}"
    }
   ]
  },
  {
   "title": "GC Live Megabytes by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Megabytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (garbage_collection_live_megabytes{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}